In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data\gsc_shipping_rates.csv')

In [3]:
df.head(10)

,date,year,month,baltic_dry_index,container_rate_usd_40ft,air_cargo_rate_usd_kg,bdi_mom_change_pct,container_yoy_pct,tanker_rate_aframax_usd_day,bulk_carrier_handysize_usd_day,supply_chain_pressure_index,on_time_delivery_pct
0,2000-01,2000,1,1239,1630,3.40,NaN,NaN,32524,4195,0.50,0.930
1,2000-02,2000,2,1210,1810,3.00,-2.34,NaN,32035,15111,0.70,0.946
2,2000-03,2000,3,1286,1660,3.31,6.28,NaN,17328,15513,0.69,0.923
3,2000-04,2000,4,1216,2050,3.18,-5.44,NaN,21573,10591,0.85,0.926
4,2000-05,2000,5,1316,1900,3.82,8.22,NaN,21748,9951,0.62,0.934
5,2000-06,2000,6,1391,1800,3.02,5.70,NaN,18404,14602,0.86,0.935
6,2000-07,2000,7,1265,1870,3.26,-9.06,NaN,26749,15485,0.77,0.936
7,2000-08,2000,8,1339,1890,3.40,5.85,NaN,13342,10721,0.65,0.909
8,2000-09,2000,9,1328,2130,3.02,-0.82,NaN,32746,5268,0.69,0.921
9,2000-10,2000,10,1416,1980,3.45,6.63,NaN,22210,10150,0.95,0.917

In [5]:
#check for null values
df.isnull().sum()

date                               0
year                               0
month                              0
baltic_dry_index                   0
container_rate_usd_40ft            0
air_cargo_rate_usd_kg              0
bdi_mom_change_pct                 1
container_yoy_pct                 12
tanker_rate_aframax_usd_day        0
bulk_carrier_handysize_usd_day     0
supply_chain_pressure_index        0
on_time_delivery_pct               0
dtype: int64

In [6]:
df.head(20)

,date,year,month,baltic_dry_index,container_rate_usd_40ft,air_cargo_rate_usd_kg,bdi_mom_change_pct,container_yoy_pct,tanker_rate_aframax_usd_day,bulk_carrier_handysize_usd_day,supply_chain_pressure_index,on_time_delivery_pct
0,2000-01,2000,1,1239,1630,3.40,NaN,NaN,32524,4195,0.50,0.930
1,2000-02,2000,2,1210,1810,3.00,-2.34,NaN,32035,15111,0.70,0.946
2,2000-03,2000,3,1286,1660,3.31,6.28,NaN,17328,15513,0.69,0.923
3,2000-04,2000,4,1216,2050,3.18,-5.44,NaN,21573,10591,0.85,0.926
4,2000-05,2000,5,1316,1900,3.82,8.22,NaN,21748,9951,0.62,0.934
5,2000-06,2000,6,1391,1800,3.02,5.70,NaN,18404,14602,0.86,0.935
6,2000-07,2000,7,1265,1870,3.26,-9.06,NaN,26749,15485,0.77,0.936
7,2000-08,2000,8,1339,1890,3.40,5.85,NaN,13342,10721,0.65,0.909
8,2000-09,2000,9,1328,2130,3.02,-0.82,NaN,32746,5268,0.69,0.921
9,2000-10,2000,10,1416,1980,3.45,6.63,NaN,22210,10150,0.95,0.917
10,2000-11,2000,11,1281,1650,3.02,-9.53,NaN,28977,12569,0.81,0.918
11,2000-12,2000,12,1413,1970,3.17,10.30,NaN,28654,9352,0.68,0.913
12,2001-01,2001,1,1319,1950,3.13,-6.65,19.63,25099,13922,0.82,0.934
13,2001-02,2001,2,1425,1780,3.24,8.04,-1.66,11501,6211,0.50,0.904
14,2001-03,2001,3,1485,1700,3.17,4.21,2.41,35393,10574,0.86,0.907
15,2001-04,2001,4,1449,1700,3.18,-2.42,-17.07,31722,5090,0.80,0.931
16,2001-05,2001,5,1431,1620,3.29,-1.24,-14.74,20764,12930,0.71,0.960
17,2001-06,2001,6,1479,1690,3.32,3.35,-6.11,26759,17436,0.89,0.933
18,2001-07,2001,7,1656,1670,3.12,11.97,-10.70,17587,10440,0.50,0.939
19,2001-08,2001,8,1513,1630,3.03,-8.64,-13.76,27508,15352,1.09,0.980

In [7]:
#remove rows with null values
df = df.dropna()

In [8]:
df.head(10)

,date,year,month,baltic_dry_index,container_rate_usd_40ft,air_cargo_rate_usd_kg,bdi_mom_change_pct,container_yoy_pct,tanker_rate_aframax_usd_day,bulk_carrier_handysize_usd_day,supply_chain_pressure_index,on_time_delivery_pct
12,2001-01,2001,1,1319,1950,3.13,-6.65,19.63,25099,13922,0.82,0.934
13,2001-02,2001,2,1425,1780,3.24,8.04,-1.66,11501,6211,0.50,0.904
14,2001-03,2001,3,1485,1700,3.17,4.21,2.41,35393,10574,0.86,0.907
15,2001-04,2001,4,1449,1700,3.18,-2.42,-17.07,31722,5090,0.80,0.931
16,2001-05,2001,5,1431,1620,3.29,-1.24,-14.74,20764,12930,0.71,0.960
17,2001-06,2001,6,1479,1690,3.32,3.35,-6.11,26759,17436,0.89,0.933
18,2001-07,2001,7,1656,1670,3.12,11.97,-10.70,17587,10440,0.50,0.939
19,2001-08,2001,8,1513,1630,3.03,-8.64,-13.76,27508,15352,1.09,0.980
20,2001-09,2001,9,1589,1710,2.77,5.02,-19.72,27141,8748,0.61,0.914
21,2001-10,2001,10,1553,2100,3.33,-2.27,6.06,23730,7857,0.50,0.908

In [9]:
#df to csv
df.to_csv('data_usable\gsc_shipping_rates_clean.csv', index=False)